#cloud-config
runcmd:
  - apt update
  - apt upgrade -y
  - apt install -y python3-pip
  - python3 -m pip install ansible==8.1.0
  - ansible-pull -U https://github.com/heiyiu/cloud-instance-helper ansible/kubernetes/setup_k8s.yml