  # create an user for running jobs
- name: Ensure group "batch" exists
  ansible.builtin.group:
    name: "{{ username }}"
    state: present
- name: create user
  ansible.builtin.user:
    name: "{{ username }}"
    comment: user for running jobs
    group: "{{ username }}"
    shell: /bin/bash