- name: download binary package
  get_url:
    url: https://get.helm.sh/helm-v3.12.0-linux-amd64.tar.gz
    dest: /tmp/helm.tar.gz
- name: Create directory for extracted helm files
  file:
    state: directory
    path: /tmp/helm
- name: Extract Helm archive
  unarchive:
    src: /tmp/helm.tar.gz
    dest: /tmp/helm
- name: move file
  ansible.builtin.copy:
    src: /tmp/helm/linux-amd64/helm 
    dest: /usr/local/bin/helm
    mode: "0755"
    owner: "{{ kube_user }}"
    group: "{{ kube_user }}"
  become: true