- name: install microk8s
  community.general.snap:
    name: microk8s
    classic: true
    channel: "1.27"
  become: true
- name: Add user to microk8s group
  ansible.builtin.user:
    name: "{{  kube_user }}"
    groups: microk8s
    append: yes
  become: true
- name: Change owner of ~/.kube directory
  ansible.builtin.file:
    path: ~/.kube
    owner: "{{ kube_user }}"
    recurse: yes
  become: true
# may require a su - $USER if the user instead of terraform runs the playbook
- name: enable microk8s plugins
  command: microk8s enable "{{ item }}"
  loop:
    - dns
    - hostpath-storage
    - helm
    - helm3
  become: true
- name: add alias to ~/.bash_aliases
  lineinfile:
    path: ~/.bash_aliases
    line: 'alias k="microk8s kubectl"'
    create: yes
- name: refresh the aliases for the current shell session
  shell: source ~/.bash_aliases
  args:
    executable: /bin/bash
# restart the node or the ssh session since newgrp creates a new subshell and does not affect the parent shell that Ansible uses