- name: create argocd ns
  kubernetes.core.k8s:
    name: argocd
    api_version: v1
    kind: Namespace
    state: present
- name: install argos
  kubernetes.core.k8s:
    namespace: argocd
    state: present
    src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml