---
- name: "vm configuration playbook"
  hosts: localhost
  connection: local
  vars:
    ansible_remote_tmp: /tmp/
    install_k0s: false
    install_k3s: true
    install_argocd: true
  tasks:
  # create a batch user for running batch jobs
  - name: create app user
    ansible.builtin.include_tasks:
      file: tasks/create_user.yml
    vars:
      username: batch
  # install libraries needed for image processing
  - name: "install python libraries"
    ansible.builtin.pip:
      name:
        - torch==2.0.0 
        - onnxruntime==1.14.1
        - accelerate==0.18.0
        # following doesn't seem to install successfully on ubuntu20
        #- diffusers[torch]==0.15.1
        - optimum[onnxruntime]==1.8.2
      extra_args: --user
    become: true
    become_user: batch
  # install a lightweight k9s distribution
  - name: "install k0s"
    ansible.builtin.include_tasks:
      file: tasks/install_k0s.yml
    vars:
      k0s_installer_path: /tmp/k0s.sh
    when: install_k0s
  - name: "install k3s"
    ansible.builtin.include_tasks:
      file: tasks/install_k3s.yml
    vars:
      k3s_installer_path: /tmp/k3s.sh
    when: install_k3s
  - name: "install argocd"
    ansible.builtin.include_tasks:
      file: tasks/install_argocd.yml
    environment:
      KUBECONFIG: /etc/rancher/k3s/k3s.yaml
    when: install_argocd and install_k3s 