---
- name: "vm configuration playbook"
  hosts: localhost
  connection: local
  vars:
    ansible_remote_tmp: /tmp/
    k0s_installer_path: /tmp/k0s.sh
  tasks:
  # create a batch user for running batch jobs
  - name: Ensure group "batch" exists
    ansible.builtin.group:
      name: batch
      state: present
  - name: create batch user
    ansible.builtin.user:
      name: batch
      comment: Batch user for running jobs
      group: batch
      shell: /bin/bash
  - name: "install python libraries"
    ansible.builtin.pip:
      name:
        - torch==2.0.0 
        - onnxruntime==1.14.1
        - accelerate==0.18.0
        # following doesn't seem to install successfully on ubuntu20
        #- diffusers[torch]==0.15.1
        - optimum[onnxruntime]==1.8.2
      extra_args: --user
    become: true
    become_user: batch
  # download and install k0s
  - name: download k0s
    ansible.builtin.get_url:
      url: https://get.k0s.sh
      dest: "{{ k0s_installer_path }}"
  - name: install k0s in single node mode
    command: bash "{{ k0s_installer_path }}" && k0s install controller --single
  - name: start k0s
    service:
      name: k0scontroller
      enabled: true
      state: started