---
- name: "vm configuration playbook"
  hosts: localhost
  connection: local
  vars:
    ansible_remote_tmp: /tmp/
    install_k0s: false
    install_k3s: true
    kubernetes_dist: k3s # can be k0s, k3s, microk8s
    install_argocd: true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  tasks:
  # create a batch user for running batch jobs
  - name: create app user
    ansible.builtin.include_tasks:
      file: tasks/create_user.yml
    vars:
      username: batch
  # install libraries needed for image processing
  # move the following into a container
  #- name: "install python libraries"
  #  ansible.builtin.pip:
  #    name:
  #      - torch==2.0.0 
  #      - onnxruntime==1.14.1
  #      - accelerate==0.18.0
        # following doesn't seem to install successfully on ubuntu20
        #- diffusers[torch]==0.15.1
  #      - optimum[onnxruntime]==1.8.2
  #    extra_args: --user
  #  become: true
  #  become_user: batch
  # install a lightweight k9s distribution
  - name: "install k0s"
    ansible.builtin.include_tasks:
      file: tasks/install_k0s.yml
    vars:
      k0s_installer_path: /tmp/k0s.sh
    when: kubernetes_dist == k0s
  - name: "install k3s"
    ansible.builtin.include_tasks:
      file: tasks/install_k3s.yml
    vars:
      k3s_installer_path: /tmp/k3s.sh
    when: kubernetes_dist == k3s
  - name: "install microk8s stack"
    ansible.builtin.include_tasks:
      file: tasks/install_microk8s_stack.yml
    vars:
      kub_user: cloud_user
    when: kubernetes_dist == microk8s   
  - name: "install argocd"
    ansible.builtin.include_tasks:
      file: tasks/install_argocd.yml
    vars:
      argocd_cm_path: files/argocd_cm.yml
    when: install_argocd and kubernetes_dist == k3s
  - name: "install cert-manager and configure for https"
    ansible.builtin.include_tasks:
      file: tasks/setup_https.yml
    when: kubernetes_dist == k3s